files:
  include: 'src/**/*.scss'
  ignore:
    - 'node_modules/**/*.*'
    - 'src/admin/**/*.*'

rules:
  brace-style: 2
  bem-depth:
    - 2
    - max-depth: 2
  border-zero:
    - 2
    - convention: '0'
  class-name-format:
    - 2
    -
      convention: hyphenatedbem
  clean-import-paths: 2
  empty-args: 2
  empty-line-between-blocks: 2
  extends-before-mixins: 2
  extends-before-declarations: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  hex-length: 2
  hex-notation:
    - 1
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  leading-zero: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - media
  nesting-depth:
    - 2
    -
      max-depth: 3
  no-color-keywords: 2
  no-css-comments: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 1
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 1
  one-declaration-per-line: 2
  property-sort-order:
    - 2
    -
      order: alphabetical
  property-units:
    - 2
    -
      global:
        - px
        - '%'
      per-property:
        border:
          - px
        font-size:
          - rem
          - px
          - '%'
        height:
          - px
          - '%'
        letter-spacing:
          - rem
          - px
        line-height:
          - rem
          - px
          - '%'
        margin:
          - px
          - '%'
        padding:
          - px
        width:
          - px
          - '%'
  quotes: 2
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
  zero-unit: 2
