{ config, ... }:
{
  xdg.configFile."tmux" = {
    source = config.lib.mega.linkConfig "tmux";
    force = true;
  };

  xdg.dataFile."tmux/nix.conf".text = ''
    # Auto-generated by Nix - DO NOT EDIT
    set -g default-shell "${config.home.profileDirectory}/bin/fish"
  '';
}
