#!/usr/bin/env bash

set -euo pipefail

# Check script is being executed appropriatly
if [[ -z "${BASH_SOURCE}" ]]; then
  msg="This file should be executed directly with \`./install\`
  and not interpreted with \`sh ./install\`"
  echo "$msg"
  exit 1
fi

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot/core"
DOTBOT_BIN="bin/dotbot"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive "dotbot/asdf"
git submodule update --init --recursive "dotbot/brewfile"
git submodule update --init --recursive "dotbot/ifplatform"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -v -d "${BASEDIR}" \
  --plugin-dir dotbot/brewfile \
  --plugin-dir dotbot/asdf \
  --plugin-dir dotbot/ifplatform \
  -c "${CONFIG}" "${@}"
  # -c "${CONFIG}"

# run ${@} 2>&1 | tee "makeinstall.log"
# run ${@} 2>&1 | tee "$HOME/$(date +'%Y-%m-%d-%H-%M-%S').log"
# run ${@}
