#!/usr/bin/env bash

###############################################################################
# .nbrc
#
# Configuration file for `nb`, a command line note-taking, bookmarking,
# and knowledge base application with encryption, search, Git-backed syncing,
# and more in a single portable script.
#
# Edit this file manually or manage settings using the `nb settings`
# subcommand. Configuration options are set as environment variables, eg:
#   export NB_ENCRYPTION_TOOL=gpg
#
# https://github.com/xwmx/nb
###############################################################################

export NB_AUTO_SYNC="${NB_AUTO_SYNC:-1}"
export NB_ENCRYPTION_TOOL="${NB_ENCRYPTION_TOOL:-openssl}" # or gpg

export NB_DEFAULT_EXTENSION="${NB_DEFAULT_EXTENSION:-md}"
export NB_LIMIT="${NB_LIMIT:-15}"
export NB_DIR="${NB_DIR:-$HOME/Documents/_nb/notebooks}"

export NB_HEADER="${NB_HEADER:-2}" # 0-3
export NB_FOOTER="${NB_FOOTER:-1}" # 0-3

# export NB_COLOR_PRIMARY="${NB_COLOR_PRIMARY:-1}"
# export NB_COLOR_SECONDARY="${NB_COLOR_SECONDARY:-239}"
export NB_COLOR_THEME="${NB_COLOR_THEME:-ocean}"
# export NB_SYNTAX_THEME="${NB_SYNTAX_THEME:-Ocean}"

export NB_ACE_ENABLED=1
export BROWSER="w3m"
export EDITOR="nvim"
# export EDITOR="nvim -c 'Goyo' -c 'norm Go' -c 'startinsert'"

export NB_INDICATOR_AUDIO=" "
export NB_INDICATOR_BOOKMARK=" "
export NB_INDICATOR_DOCUMENT=" "
export NB_INDICATOR_EBOOK="龎 "
export NB_INDICATOR_ENCRYPTED=" "
export NB_INDICATOR_FOLDER=" "
export NB_INDICATOR_IMAGE=" "
export NB_INDICATOR_PINNED=" "
export NB_INDICATOR_TODO=" "
export NB_INDICATOR_TODO_DONE="﫟"
export NB_INDICATOR_VIDEO=" "
