{ paths, ... }:
let
  inherit (paths) home notes;
  configHome = paths.config;
  shadeNextConfig = ''
    [identity]
    binary = "shade-next"
    bundle_id = "io.shade.next"
    url_scheme = "shade-next://"

    [paths]
    notes_home = "${notes}"
    captures_dir = "${notes}/captures"
    data_home = "${home}/.local/share/shade-next"
    state_home = "${home}/.local/state/shade-next"
    repo = "${home}/code/shade-next"
    debug_binary = "${home}/code/shade-next/.build/debug/shade-next"
    release_binary = "${home}/code/shade-next/.build/release/shade-next"

    [ui]
    font_family = "SF Pro Text"
    font_size = 22
    line_height = 1.3
    compact_width = 920
    compact_height = 120
    expanded_height = 560
    results_height = 480
    panel_padding = 24
    corner_radius = 24
    row_spacing = 6

    [keys]
    commit = "cmd+enter"
    search = "cmd+f"
  '';
  shadeNextFragment = ''
    -- Auto-generated by Nix - DO NOT EDIT
    return {
      app = {
        name = "shade-next",
        bundle_id = "io.shade.next",
        url_scheme = "shade-next://",
      },
      launch = {
        repo = "${home}/code/shade-next",
        config = "${configHome}/shade-next/config.toml",
        socket = "${home}/.local/state/shade-next/shade-next.sock",
        binaries = {
          debug = "${home}/code/shade-next/.build/debug/shade-next",
          release = "${home}/code/shade-next/.build/release/shade-next",
        },
      },
      chords = {
        toggle = { mods = { "cmd" }, key = "return" },
        search = { mods = { "cmd" }, key = "f" },
      },
      -- Hyper chords that launch/focus shade-next prefilled with a route.
      -- mods are extra modifiers on top of Hyper; key is the trigger.
      prefills = {
        { mods = { }, key = "p", route = "pi", focus = true },
        { mods = { }, key = "n", route = "note", focus = true },
      },
    }
  '';
in
{
  xdg.configFile."shade-next/config.toml".text = shadeNextConfig;

  xdg.dataFile."hammerspoon/fragments/shade-next.lua".text = shadeNextFragment;
}
