{ paths, ... }:
let
  inherit (paths) home notes;
  configHome = paths.config;
  shadeNextConfig = ''
    [identity]
    binary = "shade-next"
    bundle_id = "io.shade.next"
    url_scheme = "shade-next://"

    [paths]
    notes_home = "${notes}"
    captures_dir = "${notes}/captures"
    data_home = "${home}/.local/share/shade-next"
    state_home = "${home}/.local/state/shade-next"
    repo = "${home}/code/shade-next"
    debug_binary = "${home}/code/shade-next/.build/debug/shade-next"
    release_binary = "${home}/code/shade-next/.build/release/shade-next"

    [ui]
    font_family = "SF Pro Text"
    font_size = 22
    line_height = 1.3
    compact_width = 900
    compact_height = 104
    expanded_height = 560
    results_height = 480
    panel_padding = 24
    corner_radius = 24
    row_spacing = 6
    background_color = "#262B31F2"
    border_width = 1.0
    border_color = "#FFFFFF22"
    dim_unfocused = 0.5

    [keys]
    commit = "cmd+enter"
    search = "cmd+f"

    [app]
    launch_hidden = true
    live_debug = false
    # Seconds the panel may stay hidden before its composer auto-resets to the
    # launcher state (an in-progress note is always preserved). 0 disables.
    auto_reset_timeout_seconds = 300

    [editor]
    nvim_host = true

    [agent]
    # Local launcher agent. Deterministic routing runs first; low-confidence
    # route classification uses direct HTTP to local llama-server + gemma4.
    # Do not invoke pi per request on the hot typing path.
    enabled = true
    provider = "openai_compatible"
    # assist = auto on low-confidence input; manual = explicit trigger only.
    mode = "assist"
    # Agent budget; app clamps to 500-1500ms.
    timeout_ms = 1200

    [agent.openai_compatible]
    base_url = "http://127.0.0.1:18080/v1"
    model = "gemma4"
    route_max_tokens = 8
    answer_max_tokens = 128
    temperature = 0
  '';
  shadeNextFragment = ''
    -- Auto-generated by Nix - DO NOT EDIT
    return {
      app = {
        name = "shade-next",
        bundle_id = "io.shade.next",
        url_scheme = "shade-next://",
      },
      launch = {
        repo = "${home}/code/shade-next",
        config = "${configHome}/shade-next/config.toml",
        socket = "${home}/.local/state/shade-next/shade-next.sock",
        binaries = {
          debug = "${home}/code/shade-next/.build/debug/shade-next",
          release = "${home}/code/shade-next/.build/release/shade-next",
        },
      },
      chords = {
        toggle = { mods = { "cmd" }, key = "return" },
        search = { mods = { "cmd" }, key = "f" },
      },
      -- Keys inside the Hyper+n shade-next modal that launch/focus shade-next
      -- prefilled with a route.
      prefills = {
        { mods = { }, key = "p", route = "pi", focus = true },
        { mods = { }, key = "n", route = "note", focus = true },
      },
    }
  '';
in
{
  xdg.configFile."shade-next/config.toml".text = shadeNextConfig;

  xdg.dataFile."hammerspoon/fragments/shade-next.lua".text = shadeNextFragment;
}
