name: app
root: ~/code/outstand

# Runs on project start, always
on_project_start: gohome && dowork

tmux_options: -2
windows:
  - ssh-dots:
      - ssh seth-dev
      - cd ~/.dotfiles
  - code:
      - ssh seth-dev
      - cd ~/code/app
      - eval $(desk load); nvim
  - services:
      layout: vertical
      panes:
        - logs:
            - ssh seth-dev
            - cd ~/code/app
            - eval $(desk load)
        - repl:
            - ssh seth-dev
            - cd ~/code/app
            - eval $(desk load); rails console
