--# selene: allow(unused_variable)
---@diagnostic disable: unused-local

-- Visual, searchable pasteboard (ie clipboard) history
---@class spoon.Seal.plugins.pasteboard
local M = {}
spoon.Seal.plugins.pasteboard = M

-- 
-- The number of history items to keep. Defaults to 50
M.historySize = nil

-- 
-- A boolean, true if Seal should automatically load/save clipboard history. Defaults to true
M.saveHistory = nil

-- 
-- An array of UTIs to skip when saving to the history. Defaults to:
-- ```
-- {
--   "de.petermaurer.TransientPasteboardType",
--   "com.typeit4me.clipping",
--   "Pasteboard generator type",
--   "com.agilebits.onepassword",
--   "org.nspasteboard.TransientType",
--   "org.nspasteboard.ConcealedType",
--   "org.nspasteboard.AutoGeneratedType"
-- }
-- ```
M.skipUTIs = nil

