# column_width = 160
# line_endings = "Unix"
# indent_type = "Spaces"
# indent_width = 2
# quote_style = "AutoPreferSingle"
# call_parentheses = "None"


column_width = 160
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "ForceDouble"
no_call_parentheses = false
collapse_simple_statement = 'Always'
