-- if not vim.filetype then return end

vim.filetype.add({
  filename = {
    [".gitignore"] = "conf",
    ["kitty.conf"] = "kitty",
    [".env"] = "bash",
    ["Deskfile"] = "bash",
    ["tool-versions"] = "conf",
    [".tool-versions"] = "conf",
    ["default-python-packages"] = "conf",
    ["default-node-packages"] = "conf",
    ["default-gems"] = "conf",
    ["tsconfig.json"] = "jsonc",
    [".prettierrc"] = "jsonc",
    [".eslintrc"] = "jsonc",
    ["Brewfile"] = "ruby",
    ["Brewfile.mas"] = "ruby",
    ["Brewfile.cask"] = "ruby",
    ["NEOGIT_COMMIT_EDITMSG"] = "NeogitCommitMessage",
  },
  extension = {
    json = "jsonc",
    eslintrc = "jsonc",
    prettierrc = "jsonc",
    conf = "conf",
    mdx = "markdown",
    md = "markdown",
    lexs = "elixir",
    exs = "elixir",
    eex = "eelixir",
    keymap = "keymap",
    cts = "typescript",
    mts = "typescript",
  },
  pattern = {
    [".*%.conf"] = "conf",
    [".*%.theme"] = "conf",
    [".*ignore"] = "conf",
    [".nvimrc"] = "lua",
    ["default-*%-packages"] = "conf",
    [".*%.gradle"] = "groovy",
    -- [".*%.env%..*"] = "env",
    [".*env%..*"] = "bash",
    [".*%.prettierrc%..*"] = "jsonc",
    [".*%.eslintrc%..*"] = "jsonc",
    [".*%.jst.eco"] = "jst",
    [".*%.html.en"] = "html",
  },
  -- ['.*tmux.*conf$'] = 'tmux',
})
