name: "default"
windows:
  - name: "chats"
    root: "~/.dotfiles"
    panes:
      - commands:
        - irc
  - name: "services"
    root: "~/code/welltok"
    layout: tiled
    panes:
      - commands:
        - cd rewards-dashboard
        - npm install
        - npm start
      - commands:
        - cd rewards-dashboard
        - npm run mock
      - commands:
        - cd cafewell
        # - chruby ruby-2.2.3
        - npm install
        - bundle
        - bundle exec rake db:migrate
        - killport 5000 # kill moxy in case it's already running
        - killport 3000 # kill thin/rails in case it's already running
        - thin start -p 3000 -a 127.0.0.1
  - name: "code"
    root: "~/code/welltok/"
    focus: true
    panes:
      - ls -gha

