{
  config,
  paths,
  ...
}:
{
  xdg.configFile."hammerspoon" = {
    source = config.lib.mega.linkConfig "hammerspoon";
    force = true;
  };

  xdg.dataFile."hammerspoon/nix_path.lua".text = ''
    -- Auto-generated by Nix - DO NOT EDIT
    -- Note: Using /nix/var/nix/profiles/system/sw/bin because Determinate Nix
    -- doesn't create /run/current-system symlink
    NIX_PATH = "${config.home.profileDirectory}/bin:/nix/var/nix/profiles/system/sw/bin"
    NIX_ENV = {
      NOTES_HOME = "${paths.notes}",
      OBSIDIAN_HOME = "${paths.notes}",
      NVIM_DB_HOME = "${paths.nvimDb}",
      DOTS = "${paths.dotfiles}",
      XDG_CONFIG_HOME = "${paths.config}",
      XDG_DATA_HOME = "${paths.home}/.local/share",
      XDG_CACHE_HOME = "${paths.home}/.local/cache",
    }
  '';
}
