-- @see https://github.com/wincent/wincent/blob/main/aspects/nvim/files/.config/nvim/plugin/snippets.lua#L31-L40

-- local has_luasnip, luasnip = pcall(require, "luasnip")
-- if has_luasnip then
--   local fmt = require("luasnip.extras.fmt").fmt
--   local i = luasnip.insert_node

--   -- NOTE: if ~/.github-handles.json exists, use it.
--   local cab = (vim.fn.filereadable(vim.fn.expand("~/.github-handles.json")) == 1)
--       and fmt("Co-Authored-By: {}", {
--         i(1, "@handle"),
--       })
--     or fmt("Co-Authored-By: {} <{}@{}>", {
--       i(1, "Name"),
--       i(2, "user"),
--       i(3, "github.com"),
--     })
--   return {
--     s({ trig = "cab", dscr = "Co-Authored-By:" }, cab),
--   }
-- end
-- return {}
