name: app
root: ~/code/outstand

# Runs on project start, always
on_project_start: gohome && dowork

tmux_options: -2
windows:
  - chats:
      layout: main-vertical
      panes:
        - chats:
            - tmux link-window -s mega:chats -t 0 && exit
  - code:
      layout: main-vertical
      panes:
        - code:
            - mosh seth-dev
            - cd ~/code/app
            - eval $(desk load); ls
  - services:
      layout: even-horizontal
      panes:
        - logs:
            - mosh seth-dev
            - cd ~/code/app
            - eval $(desk load)
        - repl:
            - mosh seth-dev
            - cd ~/code/app
            - eval $(desk load); rails console
