name: "mega"
root: ~/.dotfiles

tmux_options: -2
windows:
  #
  # HOWTO: link `chats` to other session windows; go to other session first, then:
  # tmux link-window -s mega:chats -t 0
  #
  - chats:
      - weechat
  - dots:
      - ls
  - ssh-dots:
      - mosh seth-dev
      - cd ~/.dotfiles
      - ls
