name: "🗿 megalithic.io"
root: ~/code/megalithic.io

tmux_options: -2
windows:
  - chats:
      - tmux link-window -s mega:chats -t 0 && exit
  - code:
      layout: main-vertical
      panes:
        - code:
            - cd ~/code/megalithic.io
  - services:
      layout: even-horizontal
      panes:
        - iex server:
            - cd ~/code/megalithic.io
            - iex -S mix phx.server --open
