name: public_site
root: ~/code/outstand

# Runs on project start, always
on_project_start: gohome && dowork

tmux_options: -2
windows:
  - chats:
      - tmux link-window -s mega:chats -t 0 && exit
  - code:
      layout: main-vertical
      panes:
        - code:
            # - et seth-dev
            - cd ~/code/outstand/public-site
          # - eval $(desk load); nvim
  - services:
      layout: even-horizontal
      panes:
        - logs:
            # - et seth-dev
            - cd ~/code/outstand/public-site
            # - eval $(desk load)
        - repl:
            # - et seth-dev
            - cd ~/code/outstand/public-site
            # - eval $(desk load);
