name: public_site
root: ~/code

# Runs on project start, always
# on_project_start: gohome && dowork

tmux_options: -2
windows:
  - chats:
      - tmux link-window -s mega:chats -t 0 && exit
  - code:
      layout: main-vertical
      panes:
        - code:
            - et seth-dev
            - cd ~/code/public-site
            - eval $(desk load);
  - services:
      layout: even-horizontal
      panes:
        - logs:
            - et seth-dev
            - cd ~/code/public-site
            - eval $(desk load)
            - dev down --remove-orphans; dev up -d && dev logs -f
        - repl:
            - et seth-dev
            - cd ~/code/public-site
            - eval $(desk load);
