#!/usr/bin/env bash
# Generate project-local Pi guidance and merge the Tidewave MCP server into
# .pi/mcp.json. Run by `mise run bootstrap:pi`. Project-owned AGENTS.md is
# intentionally never touched.
set -euo pipefail

root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$root"
mkdir -p .pi
port="$(bash .config/scripts/phx-port.sh)"
append=.pi/APPEND_SYSTEM.md
m=.pi/mcp.json
begin='<!-- mise-tmpl-gen:elixir:begin -->'
end='<!-- mise-tmpl-gen:elixir:end -->'

for path in "$append" "$m"; do
  if [ -L "$path" ]; then
    echo "error: refusing to modify symlink: $root/$path" >&2
    exit 1
  fi
done
[ -e "$append" ] && [ -f "$append" ] || [ ! -e "$append" ] || {
  echo "error: Pi guidance path is not a regular file: $root/$append" >&2; exit 1;
}
[ -e "$m" ] && [ -f "$m" ] || [ ! -e "$m" ] || {
  echo "error: MCP path is not a regular file: $root/$m" >&2; exit 1;
}

# ── Stage and validate both files before replacing either one ─────────
mcp_input="$(mktemp "$root/.pi/mcp-input.XXXXXX")"
mcp_tmp="$(mktemp "$root/.pi/mcp.json.XXXXXX")"
append_tmp="$(mktemp "$root/.pi/APPEND_SYSTEM.md.XXXXXX")"
cleanup() { rm -f "$mcp_input" "$mcp_tmp" "$append_tmp"; }
trap cleanup EXIT
if [ -e "$m" ]; then
  jq -e 'type == "object" and ((.mcpServers // {}) | type == "object")' "$m" >/dev/null || {
    echo "error: expected .pi/mcp.json to contain an object and object mcpServers" >&2
    exit 1
  }
  cp "$m" "$mcp_input"
else
  printf '%s\n' '{"mcpServers":{}}' >"$mcp_input"
fi
jq --arg url "http://localhost:${port}/tidewave/mcp" \
  '.mcpServers = (.mcpServers // {})
   | .mcpServers.tidewave = {type: "streamable-http", url: $url, lifecycle: "keep-alive"}' \
  "$mcp_input" >"$mcp_tmp"
jq -e 'type == "object" and (.mcpServers | type == "object")' "$mcp_tmp" >/dev/null

# ── APPEND_SYSTEM.md: replace only our marker-delimited block ────────
block=$(cat <<'GUIDANCE'
<!-- mise-tmpl-gen:elixir:begin -->
# Elixir project guidance (generated by `mise run bootstrap:pi`)

Elixir Phoenix LiveView application.
Local tooling is managed by mise (`.config/mise.toml`).

## Development requirements

- Prefer the `tidewave` MCP server in `.pi/mcp.json` for code introspection,
  editing, REPL usage, and database access before using shell tools.

## Testing requirements

- If PostgreSQL connection errors occur during tests, reduce `POOL_SIZE`.
- Fix errors introduced by the current work, and investigate pre-existing errors
  rather than ignoring them.

## Ports

- Phoenix dev port derives from `GIT_WORKTREE`:
  `4000 + :erlang.phash2(GIT_WORKTREE, 1000)` (see `config/dev.exs`).
- `PHX_PORT` is exported by mise via `.config/scripts/phx-port.sh`.
- Tidewave MCP: `http://localhost:$PHX_PORT/tidewave/mcp` (requires Phoenix in dev).

## Tasks

- `mise run preflight` — trust config, install tools, bootstrap, start PostgreSQL
- `mise run setup` — install dependencies and prepare databases without dropping them
- `mise run db:reset` — explicitly reset dev and test databases
- `mise run start:server` — start Phoenix (`m s`)
- `mise run bootstrap` — regenerate this block and `.pi/mcp.json`

## Verification

- Run `mix format` after major changes.
- Run `mix test` after each work session.
- Run `mix check` before committing.
<!-- mise-tmpl-gen:elixir:end -->
GUIDANCE
)
existing=""
[ -e "$append" ] && existing="$(cat "$append")"
begin_count="$(printf '%s' "$existing" | awk -v marker="$begin" 'index($0, marker) { n++ } END { print n+0 }')"
end_count="$(printf '%s' "$existing" | awk -v marker="$end" 'index($0, marker) { n++ } END { print n+0 }')"
if [ "$begin_count" -gt 0 ] || [ "$end_count" -gt 0 ]; then
  [ "$begin_count" -eq 1 ] && [ "$end_count" -eq 1 ] || {
    echo "error: expected exactly one generated block in $root/$append" >&2; exit 1;
  }
  before="${existing%%"$begin"*}"
  after="${existing#*"$end"}"
  printf '%s%s%s\n' "$before" "$block" "$after" >"$append_tmp"
else
  if [ -n "$existing" ]; then
    printf '%s\n\n%s\n' "$existing" "$block" >"$append_tmp"
  else
    printf '%s\n' "$block" >"$append_tmp"
  fi
fi
# Final validation occurs before either staged file is installed.
jq empty "$mcp_tmp" >/dev/null
[ -s "$append_tmp" ]

# Both replacements happen only after all validation has succeeded. Each mv is
# atomic for its individual file; no existing symlink is ever followed.
mv "$append_tmp" "$append"
mv "$mcp_tmp" "$m"
trap - EXIT

echo "bootstrapped .pi (tidewave -> http://localhost:${port}/tidewave/mcp)"
