#!/usr/bin/env bash
# Generate project-local Pi guidance (.pi/APPEND_SYSTEM.md) and the Pidewave
# URL (.pi/mcp.json). Run by `mise run bootstrap:pi`. Project-owned AGENTS.md is
# intentionally never touched.
#
# Must run under macOS /bin/bash 3.2 as well as current Bash: no heredoc inside
# $(...), which Bash 3.2 misparses, and no EXIT trap, which makes Bash 3.2 exit
# 0 after a parse error.
set -euo pipefail

cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
mcp=.pi/mcp.json
append=.pi/APPEND_SYSTEM.md
begin='<!-- mise-tmpl-gen:elixir:begin -->'
end='<!-- mise-tmpl-gen:elixir:end -->'
# Stored literally; ACP (acp.ts) resolves it once per Pi session.
# shellcheck disable=SC2016
url='http://localhost:${PHX_PORT}/tidewave/mcp'
nl=$'\n'

for f in "$mcp" "$append"; do
  if [ -L "$f" ] || { [ -e "$f" ] && [ ! -f "$f" ]; }; then
    echo "error: refusing to modify non-regular file or symlink: $PWD/$f" >&2
    exit 1
  fi
done

# Remove only the old generated mcpServers.tidewave entry (custom definitions
# need manual migration) and keep an existing pidewave.url.
# shellcheck disable=SC2016 # $url is a jq variable
filter='
if type != "object" or ((.mcpServers // {}) | type) != "object" then
	error("expected .pi/mcp.json to contain an object and object mcpServers")
else . end
| .mcpServers //= {}
| if (.mcpServers | has("tidewave") | not) then .
  elif .mcpServers.tidewave == {type: "streamable-http", url: $url, lifecycle: "keep-alive"} then del(.mcpServers.tidewave)
  else error("custom tidewave definition: migrate it to pidewave.url manually") end
| .pidewave //= {}
| if (.pidewave | has("url") | not) then .pidewave.url = $url
  elif (.pidewave.url | type) == "string" and (.pidewave.url | length) > 0 then .
  else error("pidewave.url must be a non-empty string") end
'

IFS= read -r -d '' block <<'GUIDANCE' || true
<!-- mise-tmpl-gen:elixir:begin -->
# Elixir project guidance (generated by `mise run bootstrap:pi`)

Elixir Phoenix LiveView application.
Local tooling is managed by mise (`.config/mise.toml`).

## Development requirements

- Tidewave (MCP server `tidewave`, registered by Pi's `acp.ts` extension) is the
  required tool for anything that touches the running Elixir app. Call it through
  the MCP proxy; runtime registrations do not expose direct tools.
  - Never run `mix run -e`, `iex`, `elixir -e`, or `mix run` scripts through
    bash to evaluate code; use `tidewave_project_eval`.
  - Never run `psql` or `mix ecto` queries to inspect data; use
    `tidewave_execute_sql_query`.
  - Never look up a dependency's docs with `rg` in `deps/` or
    `mix usage_rules.docs`; use `tidewave_get_docs`.
  - Never `rg 'def name'` to find a definition; use
    `tidewave_get_source_location`.
  - Never tail `log/` files for runtime errors; use `tidewave_get_logs`.
  - Never drive the dev site with curl or a browser MCP for LiveView checks;
    use `tidewave_browser_eval`.
  - Bash remains for git, mise tasks, `mix format`, `mix test`, `mix check`,
    and file searches outside the running app.
  - If Tidewave is unreachable (Phoenix down, port changed), say so and
    reconnect (`/mcp reconnect tidewave`) before falling back to bash.

## Testing requirements

- If PostgreSQL connection errors occur during tests, reduce `POOL_SIZE`.
- Fix errors introduced by the current work, and investigate pre-existing errors
  rather than ignoring them.

## Ports

- Phoenix dev port derives from `GIT_WORKTREE`:
  `4000 + :erlang.phash2(GIT_WORKTREE, 1000)` (see `config/dev.exs`).
- `PHX_PORT` is exported by mise via the dotfiles template `phx-port.sh`.
- Tidewave MCP: `http://localhost:$PHX_PORT/tidewave/mcp` (requires Phoenix in dev);
  `.pi/mcp.json` stores the literal `${PHX_PORT}` in `pidewave.url`. ACP resolves
  it once per Pi session. Reload Pi after changing the URL; restart Pi from
  the updated shell environment after changing an environment variable.
- With a deferred MCP runtime, use an MCP operation (such as `/mcp reconnect
  tidewave`) to initialize it. Cmd+Shift+C stays inactive until connected.
- Do not add Tidewave to `.mcp.json` or `mcpServers`; that shadows the ACP
  registration.

## Tasks

- `mise run preflight` — trust config, install tools, bootstrap, start PostgreSQL
- `mise run setup` — install dependencies and prepare databases without dropping them
- `mise run db:reset` — explicitly reset dev and test databases
- `mise run start:server` — start Phoenix (`m s`)
- `mise run bootstrap` — regenerate this block and `.pi/mcp.json`

## Verification

- Run `mix format` after major changes.
- Run `mix test` after each work session.
- Run `mix check` before committing.
<!-- mise-tmpl-gen:elixir:end -->
GUIDANCE
block="${block%"$nl"}"

# Build both outputs before writing either file.
mcp_in='{}'
[ ! -e "$mcp" ] || mcp_in="$(cat "$mcp")"
mcp_out="$(printf '%s\n' "$mcp_in" | jq -e --arg url "$url" "$filter")"

existing=''
[ ! -e "$append" ] || existing="$(cat "$append")"
counts="$(printf '%s\n' "$existing" | awk -v b="$begin" -v e="$end" 'index($0, b) { nb++ } index($0, e) { ne++ } END { print nb + 0, ne + 0 }')"
case "$counts" in
  "0 0") guidance="${existing:+$existing$nl$nl}$block" ;;
  "1 1") guidance="${existing%%"$begin"*}$block${existing#*"$end"}" ;;
  *)
    echo "error: expected exactly one generated block in $PWD/$append" >&2
    exit 1
    ;;
esac

mkdir -p .pi
mcp_tmp="$(mktemp "$mcp.XXXXXX")"
append_tmp="$(mktemp "$append.XXXXXX")"
printf '%s\n' "$mcp_out" >"$mcp_tmp"
printf '%s\n' "$guidance" >"$append_tmp"
# Each mv is atomic and replaces the path itself, never a symlink target.
mv "$append_tmp" "$append"
mv "$mcp_tmp" "$mcp"

# shellcheck disable=SC2016 # literal ${PHX_PORT} is the stored value
echo 'bootstrapped .pi (pidewave.url -> http://localhost:${PHX_PORT}/tidewave/mcp, registered by acp.ts)'
