# Shared home-manager configuration for all hosts
# Host-specific overrides go in home/<hostname>.nix
{
  config,
  pkgs,
  lib,
  inputs,
  username,
  hostname,
  version,
  paths,
  ...
}: {
  imports = [
    ./lib.nix
    # ./mac-aliases.nix
    ./modules/settings-sync.nix
    ./rust.nix
    ./packages.nix
    ./services.nix
    ./accounts.nix
    # AI tooling
    ./programs/claude-code
    ./programs/ollama
    ./programs/omlx
    ./programs/pi-coding-agent
    # Browsers
    ./programs/brave-browser-nightly
    ./programs/firefox
    ./programs/helium-browser
    # Email
    ./programs/aerc
    ./programs/khard
    ./programs/mailmate
    ./programs/mbsync
    ./programs/msmtp
    ./programs/notmuch
    # Shells / prompts
    ./programs/fish
    ./programs/starship
    # Misc programs
    ./programs/1password
    ./programs/agenix
    ./programs/discord
    ./programs/fzf
    ./programs/ghostty
    ./programs/jj
    ./programs/nvim
    ./programs/shade
    # ./programs/worktrunk
  ];

  home.username = username;
  home.homeDirectory = paths.home;
  home.stateVersion = version;
  home.sessionPath = [
    paths.localBin
    paths.bin
    "${paths.dotfiles}/bin"
    "${paths.cargoHome}/bin"
  ];

  home.sessionVariables = {
    XDG_DATA_DIRS = "${config.home.profileDirectory}/share:${"\${GHOSTTY_SHELL_INTEGRATION_XDG_DIR:+\$GHOSTTY_SHELL_INTEGRATION_XDG_DIR:}"}$XDG_DATA_DIRS";

    # Make Nix-provided pkg-config files visible to builds
    PKG_CONFIG_PATH = "${config.home.profileDirectory}/lib/pkgconfig:${config.home.profileDirectory}/share/pkgconfig";
  };

  home.file =
    {
      # Note: ~/Applications is managed by macOS with special permissions - don't use home.file for it
      "code/.keep".text = "";
      "src/.keep".text = "";
      "tmp/.keep".text = "";
      "_screenshots/.keep".text = "";
      ".hushlogin".text = "";
      "bin".source = config.lib.mega.linkBin;
      ".editorconfig".text = ''
        root = true
        [*]
        indent_style = space
        indent_size = 2
        end_of_line = lf
        insert_final_newline = true
        trim_trailing_whitespace=true
        charset = utf-8
      '';
      ".ignore".source = ./git/tool-ignore;
      ".gitignore".source = ./git/gitignore;
      ".gitconfig".source = ./git/gitconfig;
      ".ssh/config".source = config.lib.mega.linkConfig "ssh/config";
      ".ssh/allowed_signers".text = "seth@megalithic.io ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICyxphJ0fZhJP6OQeYMsGNQ6E5ZMVc/CQdoYrWYGPDrh";
      "Library/Application Support/espanso".source = config.lib.mega.linkConfig "espanso";
      "iclouddrive".source =
        config.lib.file.mkOutOfStoreSymlink "${paths.home}/Library/Mobile Documents/com~apple~CloudDocs";
    }
    // lib.optionalAttrs
    (builtins.pathExists "${paths.home}/Library/CloudStorage/ProtonDrive-seth@megalithic.io-folder")
    {
      "protondrive".source =
        config.lib.file.mkOutOfStoreSymlink "${paths.home}/Library/CloudStorage/ProtonDrive-seth@megalithic.io-folder";
    };

  home.preferXdgDirectories = true;

  # Disable default home-manager app linking (to ~/Applications/Home Manager Apps)
  # We use our own mkAppActivation which supports ~/Applications directly.
  home.activation.copyApplications = lib.mkForce "";

  # ALSO disable the specific 'copyApps' script if it's separate from 'copyApplications'
  home.activation.copyApps = lib.mkForce "";

  home.activation.linkSystemApplications = lib.hm.dag.entryAfter ["writeBoundary"] (
    lib.mega.mkAppActivation {
      inherit pkgs;
      packages = config.home.packages;
      targetDir = "~/Applications";
      metadataSubdir = "user-apps";
    }
  );

  home.activation.setWallpaper = lib.hm.dag.entryAfter ["writeBoundary"] ''
    WALLPAPER="${paths.dotfiles}/assets/bokeh_dark.jpg"
    if [ -f "$WALLPAPER" ]; then
      run ${pkgs.desktoppr}/bin/desktoppr "$WALLPAPER"
    fi
  '';

  home.activation.configureObsidian = lib.hm.dag.entryAfter ["writeBoundary"] ''
    OBSIDIAN_CONFIG="${paths.icloud}/Documents/_notes/.obsidian/app.json"
    if [ -d "$(dirname "$OBSIDIAN_CONFIG")" ]; then
      [ -f "$OBSIDIAN_CONFIG" ] || echo '{}' > "$OBSIDIAN_CONFIG"
      ${pkgs.jq}/bin/jq -s '.[0] * .[1]' \
        "$OBSIDIAN_CONFIG" \
        <(echo '{"attachmentFolderPath": "assets"}') \
        > "$OBSIDIAN_CONFIG.tmp" && mv "$OBSIDIAN_CONFIG.tmp" "$OBSIDIAN_CONFIG"
    fi
  '';

  xdg.enable = true;

  xdg.configFile."ghostty".source = config.lib.mega.linkConfig "ghostty";
  xdg.configFile."ghostty".force = true;

  xdg.configFile."hammerspoon".source = config.lib.mega.linkConfig "hammerspoon";
  xdg.configFile."hammerspoon".force = true;

  xdg.dataFile."hammerspoon/nix_path.lua".text = ''
    -- Auto-generated by Nix - DO NOT EDIT
    -- Note: Using /nix/var/nix/profiles/system/sw/bin because Determinate Nix
    -- doesn't create /run/current-system symlink
    NIX_PATH = "${config.home.profileDirectory}/bin:/nix/var/nix/profiles/system/sw/bin"
    NIX_ENV = {
      NOTES_HOME = "${paths.notes}",
      OBSIDIAN_HOME = "${paths.notes}",
      NVIM_DB_HOME = "${paths.nvimDb}",
      DOTS = "${paths.dotfiles}",
      XDG_CONFIG_HOME = "${paths.config}",
      XDG_DATA_HOME = "${paths.home}/.local/share",
      XDG_CACHE_HOME = "${paths.home}/.local/cache",
    }
  '';

  xdg.configFile."tmux".source = config.lib.mega.linkConfig "tmux";
  xdg.configFile."tmux".force = true;

  xdg.dataFile."tmux/nix.conf".text = ''
    # Auto-generated by Nix - DO NOT EDIT
    set -g default-shell "${config.home.profileDirectory}/bin/fish"
  '';

  xdg.configFile."kitty".source = config.lib.mega.linkConfig "kitty";
  xdg.configFile."kitty".force = true;

  # Kanata keyboard configs - out-of-store symlinks for dynamic switching
  # macbook.kbd: normal config with home row mods
  # macbook-disabled.kbd: blocks internal keyboard when external keyboard connected
  # kanata.kbd: active config, dynamically switched by Hammerspoon dock watcher
  #            (defaults to macbook.kbd, dock watcher switches based on external keyboard)
  # kanata config profiles - kanata.kbd symlink is managed by darwin activation
  # script and switched dynamically by Hammerspoon dock watcher
  xdg.configFile."kanata/macbook.kbd" = {
    source = config.lib.mega.linkConfig "kanata/macbook.kbd";
    force = true;
  };
  xdg.configFile."kanata/macbook-disabled.kbd" = {
    source = config.lib.mega.linkConfig "kanata/macbook-disabled.kbd";
    force = true;
  };

  xdg.configFile."zsh".source = ./zsh;
  xdg.configFile."zsh".force = true;

  xdg.configFile."neomd/config.toml".text = ''
  '';

  xdg.configFile."process-compose/shortcuts.yaml".text = ''
    shortcuts:
      log_follow:
        shortcut: Ctrl-F
        toggle_description:
          false: Follow Off
          true: Follow On
      log_screen:
        shortcut: Ctrl-L
        toggle_description:
          false: Half Screen
          true: Full Screen
      log_wrap:
        shortcut: Ctrl-W
        toggle_description:
          false: Wrap Off
          true: Wrap On
      process_restart:
        shortcut: Ctrl-R
        description: Restart
      process_screen:
        shortcut: Ctrl-P
        toggle_description:
          false: Half Screen
          true: Full Screen
      process_start:
        shortcut: Ctrl-S
        description: Start
      process_stop:
        shortcut: Ctrl-X
        description: Stop
      quit:
        shortcut: Ctrl-Q
        description: Quit
  '';

  xdg.configFile."process-compose/theme.yaml".text = ''
    style:
      body:
        bgColor: '#2e353c'
        fgColor: '#d3c6aa'
        borderColor: '#475258'
        secondaryTextColor: '#859289'
        tertiaryTextColor: '#7a8478'
      stat_table:
        keyFgColor: '#a7c080'
        valueFgColor: '#d3c6aa'
        logoColor: '#7fbbb3'
      proc_table:
        fgColor: '#d3c6aa'
        fgWarning: '#dbbc7f'
        fgPending: '#7fbbb3'
        fgCompleted: '#a7c080'
        fgError: '#e67e80'
      help:
        fgColor: '#d3c6aa'
        keyColor: '#a7c080'
      dialog:
        bgColor: '#343f44'
        fgColor: '#d3c6aa'
        buttonBgColor: '#475258'
        buttonFgColor: '#d3c6aa'
        labelFgColor: '#a7c080'
        fieldBgColor: '#2e353c'
        fieldFgColor: '#d3c6aa'
  '';

  xdg.configFile."karabiner/karabiner.json".text = builtins.readFile ./karabiner/karabiner.json;
  xdg.configFile."karabiner/karabiner.json".force = true;

  xdg.configFile."surfingkeys/config.js".text = builtins.readFile ./surfingkeys/config.js;
  xdg.configFile."eza/theme.yml".text = ''
    colourful: true

    # Everforest Medium Palette
    # Background: #2d353b
    # Foreground: #d3c6aa
    # Black: #343f44
    # Red: #e67e80
    # Green: #a7c080
    # Yellow: #dbbc7f
    # Blue: #7fbbb3
    # Magenta: #d699b6
    # Cyan: #83c092
    # White: #d3c6aa
    # Gray: #859289
    # Bright Black: #475258
    # Bright Red: #e67e80
    # Bright Green: #a7c080
    # Bright Yellow: #dbbc7f
    # Bright Blue: #7fbbb3
    # Bright Magenta: #d699b6
    # Bright Cyan: #83c092
    # Bright White: #d3c6aa

    filekinds:
      normal: { foreground: "#d3c6aa" }
      directory: { foreground: "#e69875" }
      symlink: { foreground: "#859289" }
      pipe: { foreground: "#475258" }
      block_device: { foreground: "#e67e80" }
      char_device: { foreground: "#dbbc7f" }
      socket: { foreground: "#343f44" }
      special: { foreground: "#d699b6" }
      executable: { foreground: "#a7c080" }
      mount_point: { foreground: "#475258" }

    perms:
      user_read: { foreground: "#859289" }
      user_write: { foreground: "#475258" }
      user_execute_file: { foreground: "#a7c080" }
      user_execute_other: { foreground: "#a7c080" }
      group_read: { foreground: "#859289" }
      group_write: { foreground: "#475258" }
      group_execute: { foreground: "#a7c080" }
      other_read: { foreground: "#859289" }
      other_write: { foreground: "#475258" }
      other_execute: { foreground: "#a7c080" }
      special_user_file: { foreground: "#d699b6" }
      special_other: { foreground: "#475258" }
      attribute: { foreground: "#859289" }

    size:
      major: { foreground: "#859289" }
      minor: { foreground: "#e69875" }
      number_byte: { foreground: "#859289" }
      number_kilo: { foreground: "#859289" }
      number_mega: { foreground: "#83c092" }
      number_giga: { foreground: "#d699b6" }
      number_huge: { foreground: "#d699b6" }
      unit_byte: { foreground: "#859289" }
      unit_kilo: { foreground: "#83c092" }
      unit_mega: { foreground: "#d699b6" }
      unit_giga: { foreground: "#d699b6" }
      unit_huge: { foreground: "#e69875" }

    users:
      user_you: { foreground: "#dbbc7f" }
      user_root: { foreground: "#e67e80" }
      user_other: { foreground: "#d699b6" }
      group_yours: { foreground: "#859289" }
      group_other: { foreground: "#475258" }
      group_root: { foreground: "#e67e80" }

    links:
      normal: { foreground: "#e69875" }
      multi_link_file: { foreground: "#83c092" }

    git:
      new: { foreground: "#a7c080" }
      modified: { foreground: "#dbbc7f" }
      deleted: { foreground: "#e67e80" }
      renamed: { foreground: "#83c092" }
      typechange: { foreground: "#d699b6" }
      ignored: { foreground: "#475258" }
      conflicted: { foreground: "#e67e80" }

    git_repo:
      branch_main: { foreground: "#859289" }
      branch_other: { foreground: "#d699b6" }
      git_clean: { foreground: "#a7c080" }
      git_dirty: { foreground: "#e67e80" }

    security_context:
      colon: { foreground: "#859289" }
      user: { foreground: "#e69875" }
      role: { foreground: "#d699b6" }
      typ: { foreground: "#475258" }
      range: { foreground: "#d699b6" }

    file_type:
      image: { foreground: "#dbbc7f" }
      video: { foreground: "#e67e80" }
      music: { foreground: "#e69875" }
      lossless: { foreground: "#475258" }
      crypto: { foreground: "#343f44" }
      document: { foreground: "#859289" }
      compressed: { foreground: "#d699b6" }
      temp: { foreground: "#e67e80" }
      compiled: { foreground: "#83c092" }
      build: { foreground: "#475258" }
      source: { foreground: "#a7c080" }

    punctuation: { foreground: "#859289" }
    date: { foreground: "#83c092" }
    inode: { foreground: "#859289" }
    blocks: { foreground: "#859289" }
    header: { foreground: "#859289" }
    octal: { foreground: "#e69875" }
    flags: { foreground: "#d699b6" }

    symlink_path: { foreground: "#e69875" }
    control_char: { foreground: "#83c092" }
    broken_symlink: { foreground: "#e67e80" }
    broken_path_overlay: { foreground: "#859289" }
  '';

  fonts = {
    fontconfig.enable = true;
  };

  programs = {
    home-manager.enable = true;

    # speed up rebuilds // HT: @tmiller
    man.generateCaches = false;

    git = {
      enable = true;
      package = pkgs.gitFull;
      includes = [
        {path = "~/.gitconfig";}
      ];

      # gpg.ssh.program is set in home/common/programs/1password
      settings.gpg.ssh.allowedSignersFile = "~/.ssh/allowed_signers";
      settings.gpg.format = "ssh";
      settings.user.signingkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICyxphJ0fZhJP6OQeYMsGNQ6E5ZMVc/CQdoYrWYGPDrh";
      settings.commit.gpgSign = true;
    };

    direnv = {
      enable = true;
      enableZshIntegration = true;
      nix-direnv.enable = true;
      mise.enable = true;
      config = {
        global.load_dotenv = true;
        global.warn_timeout = 0;
        global.hide_env_diff = true;
        whitelist.prefix = [config.home.homeDirectory];
      };
    };

    nh = {
      enable = true;
      flake = "${config.home.homeDirectory}/.dotfiles/";
      clean = {
        enable = true;
        extraArgs = "--keep-since 8d"; # Time-based: keep generations from last 8 days
      };
    };

    # yazi = import ./yazi/default.nix {inherit config pkgs lib;};

    htop = {
      enable = true;
      settings = {
        sort_direction = true;
        sort_key = "PERCENT_CPU";
      };
    };

    zoxide = {
      enable = true;
      enableFishIntegration = true;
      enableZshIntegration = true;
    };

    # programs.ssh IdentityAgent set in home/common/programs/1password

    mise = {
      enable = true;
      enableFishIntegration = true;
      enableZshIntegration = true;
      globalConfig.settings = {
        auto_install = true;
        experimental = true;
        verbose = false;
      };

      # globalConfig = {
      #   tools = {
      #     elixir = "1.18.4-otp-27"; # alts: 1.18.4-otp-28
      #     erlang = "27.3.4.1"; # alts: 28.0.1
      #     python = "3.13.4";
      #     rust = "beta";
      #     node = "lts";
      #     pnpm = "latest";
      #     aws-cli = "2";
      #   };
      # };
    };

    eza = {
      enable = true;
      enableZshIntegration = true;
      enableFishIntegration = true;
      colors = "always";
      git = true;
      icons = "always";
      extraOptions = [
        "-lah"
        "--group-directories-first"
        "--color-scale"
      ];
    };

    bat = {
      enable = true;
      # bat-extras disabled — all of them pull in nushell as a build dep
      # extraPackages = with pkgs.bat-extras; [ batgrep prettybat batman ];
      config = {
        theme = "everforest";
      };
      themes = {
        everforest = {
          src =
            pkgs.fetchFromGitHub {
              owner = "neuromaancer";
              repo = "everforest_collection";
              rev = "ec3936e65699f38f8a9b1468d6ac20a25423d5af"; # pinned
              sha256 = "HQQzmSYcQY4jYyk7zyxdOSJylqJl4aBobT37pST6AXE=";
            }
            + "/bat";

          file = "everforest-soft.tmtheme";
        };
      };
    };

    ripgrep = {
      enable = true;
    };

    fd = {
      enable = true;
      ignores = [
        ".git"
        ".jj"
        ".direnv"
        "pkg"
        "Library"
        ".Trash"
      ];
    };

    television = {
      enable = false;
      enableFishIntegration = false;
    };

    k9s.enable = true;

    jq.enable = true;

    tiny = {
      enable = true;
      settings = {
        servers = [
          {
            addr = "irc.libera.chat";
            port = 6697;
            tls = true;
            realname = "Seth";
            nicks = ["replicant"];
            join = [
              "#nethack"
              "#nixos"
              "#neovim"
            ];
          }
        ];
        defaults = {
          nicks = ["replicant"];
          realname = "Seth";
          join = [];
          tls = true;
        };
      };
    };
  };
}
