# Shared home-manager configuration for all hosts
# Host-specific overrides go in home/<hostname>.nix
{
  config,
  pkgs,
  lib,
  inputs,
  username,
  version,
  paths,
  ...
}:
let
  programEntries = builtins.readDir ./programs;
  programModules = builtins.filter (
    name:
    programEntries.${name} == "directory"
    && builtins.pathExists ./programs/${name}/default.nix
    && (name != "claude-code")
    && (name != "worktrunk" || inputs ? worktrunk)
  ) (builtins.attrNames programEntries);
  programImports = map (name: ./programs/${name}) programModules;
in
{
  imports = [
    ./lib.nix
    ./modules/settings-sync.nix
    ./packages.nix
    ./services.nix
    ./accounts.nix
  ]
  ++ programImports;

  home.username = username;
  home.homeDirectory = paths.home;
  home.stateVersion = version;
  home.sessionPath = [
    paths.localBin
    paths.bin
    "${paths.dotfiles}/bin"
    "${paths.cargoHome}/bin"
  ];

  home.sessionVariables = {
    XDG_DATA_DIRS = "${config.home.profileDirectory}/share:${"\${GHOSTTY_SHELL_INTEGRATION_XDG_DIR:+\$GHOSTTY_SHELL_INTEGRATION_XDG_DIR:}"}$XDG_DATA_DIRS";

    # Make Nix-provided pkg-config files visible to builds
    PKG_CONFIG_PATH = "${config.home.profileDirectory}/lib/pkgconfig:${config.home.profileDirectory}/share/pkgconfig";
  };

  home.file = {
    # Note: ~/Applications is managed by macOS with special permissions - don't use home.file for it
    "code/.keep".text = "";
    "src/.keep".text = "";
    "tmp/.keep".text = "";
    "_screenshots/.keep".text = "";
    ".hushlogin".text = "";
    "bin".source = config.lib.mega.linkBin;
    ".editorconfig".text = ''
      root = true
      [*]
      indent_style = space
      indent_size = 2
      end_of_line = lf
      insert_final_newline = true
      trim_trailing_whitespace=true
      charset = utf-8
    '';
    "Library/Application Support/espanso".source = config.lib.mega.linkConfig "espanso";
    "iclouddrive".source =
      config.lib.file.mkOutOfStoreSymlink "${paths.home}/Library/Mobile Documents/com~apple~CloudDocs";
  }
  //
    lib.optionalAttrs
      (builtins.pathExists "${paths.home}/Library/CloudStorage/ProtonDrive-seth@megalithic.io-folder")
      {
        "protondrive".source =
          config.lib.file.mkOutOfStoreSymlink "${paths.home}/Library/CloudStorage/ProtonDrive-seth@megalithic.io-folder";
      };

  home.preferXdgDirectories = true;

  home.activation.linkSystemApplications = lib.hm.dag.entryAfter [ "writeBoundary" ] (
    lib.mega.mkAppActivation {
      inherit pkgs;
      packages = config.mega.customApps;
    }
  );

  home.activation.setWallpaper = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    WALLPAPER="${paths.dotfiles}/assets/bokeh_dark.jpg"
    if [ -f "$WALLPAPER" ]; then
      run ${pkgs.desktoppr}/bin/desktoppr "$WALLPAPER"
    fi
  '';

  home.activation.configureObsidian = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    OBSIDIAN_CONFIG="${paths.icloud}/Documents/_notes/.obsidian/app.json"
    if [ -d "$(dirname "$OBSIDIAN_CONFIG")" ]; then
      [ -f "$OBSIDIAN_CONFIG" ] || echo '{}' > "$OBSIDIAN_CONFIG"
      ${pkgs.jq}/bin/jq -s '.[0] * .[1]' \
        "$OBSIDIAN_CONFIG" \
        <(echo '{"attachmentFolderPath": "assets"}') \
        > "$OBSIDIAN_CONFIG.tmp" && mv "$OBSIDIAN_CONFIG.tmp" "$OBSIDIAN_CONFIG"
    fi
  '';

  xdg.enable = true;

  xdg.configFile."hammerspoon".source = config.lib.mega.linkConfig "hammerspoon";
  xdg.configFile."hammerspoon".force = true;

  xdg.dataFile."hammerspoon/nix_path.lua".text = ''
    -- Auto-generated by Nix - DO NOT EDIT
    -- Note: Using /nix/var/nix/profiles/system/sw/bin because Determinate Nix
    -- doesn't create /run/current-system symlink
    NIX_PATH = "${config.home.profileDirectory}/bin:/nix/var/nix/profiles/system/sw/bin"
    NIX_ENV = {
      NOTES_HOME = "${paths.notes}",
      OBSIDIAN_HOME = "${paths.notes}",
      NVIM_DB_HOME = "${paths.nvimDb}",
      DOTS = "${paths.dotfiles}",
      XDG_CONFIG_HOME = "${paths.config}",
      XDG_DATA_HOME = "${paths.home}/.local/share",
      XDG_CACHE_HOME = "${paths.home}/.local/cache",
    }
  '';

  xdg.configFile."tmux".source = config.lib.mega.linkConfig "tmux";
  xdg.configFile."tmux".force = true;

  xdg.dataFile."tmux/nix.conf".text = ''
    # Auto-generated by Nix - DO NOT EDIT
    set -g default-shell "${config.home.profileDirectory}/bin/fish"
  '';

  xdg.configFile."kitty".source = config.lib.mega.linkConfig "kitty";
  xdg.configFile."kitty".force = true;

  # Kanata keyboard configs - out-of-store symlinks for dynamic switching
  # macbook.kbd: normal config with home row mods
  # macbook-disabled.kbd: blocks internal keyboard when external keyboard connected
  # kanata.kbd: active config, dynamically switched by Hammerspoon dock watcher
  #            (defaults to macbook.kbd, dock watcher switches based on external keyboard)
  # kanata config profiles - kanata.kbd symlink is managed by darwin activation
  # script and switched dynamically by Hammerspoon dock watcher
  xdg.configFile."kanata/macbook.kbd" = {
    source = config.lib.mega.linkConfig "kanata/macbook.kbd";
    force = true;
  };
  xdg.configFile."kanata/macbook-disabled.kbd" = {
    source = config.lib.mega.linkConfig "kanata/macbook-disabled.kbd";
    force = true;
  };

  xdg.configFile."neomd/config.toml".text = "";

  xdg.configFile."process-compose/shortcuts.yaml".text = ''
    shortcuts:
      log_follow:
        shortcut: Ctrl-F
        toggle_description:
          false: Follow Off
          true: Follow On
      log_screen:
        shortcut: Ctrl-L
        toggle_description:
          false: Half Screen
          true: Full Screen
      log_wrap:
        shortcut: Ctrl-W
        toggle_description:
          false: Wrap Off
          true: Wrap On
      process_restart:
        shortcut: Ctrl-R
        description: Restart
      process_screen:
        shortcut: Ctrl-P
        toggle_description:
          false: Half Screen
          true: Full Screen
      process_start:
        shortcut: Ctrl-S
        description: Start
      process_stop:
        shortcut: Ctrl-X
        description: Stop
      quit:
        shortcut: Ctrl-Q
        description: Quit
  '';

  xdg.configFile."process-compose/theme.yaml".text = ''
    style:
      body:
        bgColor: '#2e353c'
        fgColor: '#d3c6aa'
        borderColor: '#475258'
        secondaryTextColor: '#859289'
        tertiaryTextColor: '#7a8478'
      stat_table:
        keyFgColor: '#a7c080'
        valueFgColor: '#d3c6aa'
        logoColor: '#7fbbb3'
      proc_table:
        fgColor: '#d3c6aa'
        fgWarning: '#dbbc7f'
        fgPending: '#7fbbb3'
        fgCompleted: '#a7c080'
        fgError: '#e67e80'
      help:
        fgColor: '#d3c6aa'
        keyColor: '#a7c080'
      dialog:
        bgColor: '#343f44'
        fgColor: '#d3c6aa'
        buttonBgColor: '#475258'
        buttonFgColor: '#d3c6aa'
        labelFgColor: '#a7c080'
        fieldBgColor: '#2e353c'
        fieldFgColor: '#d3c6aa'
  '';

  fonts = {
    fontconfig.enable = true;
  };

  programs.home-manager.enable = true;

  # use copyApps for GUI apps (works with Spotlight)
  targets.darwin.linkApps.enable = false;
  targets.darwin.copyApps.enable = true;
}
