require("preflight")
require("config")
require("bindings")
require("watchers"):start({ "bluetooth", "usb", "screen", "app", "url" })
require("ptt")
require("quitter")
require("wip")

hs.notify.withdrawAll()
hs.notify.new({ title = "hammerspork", subTitle = "config is loaded." }):send()
