let g:polyglot_disabled = [
      \ 'typescript',
      \ 'typescriptreact',
      \ 'typescript.tsx',
      \ 'javascriptreact',
      \ 'markdown',
      \ 'md',
      \ 'graphql',
      \ 'tsx',
      \ 'jsx',
      \ 'sass',
      \ 'scss',
      \ 'css',
      \ 'elm',
      \ 'elixir',
      \ 'eelixir',
      \ 'ex',
      \ 'exs'
      \ ]
