#!/bin/zsh

cat $DOTS/python/packages | xargs pip install --upgrade --user
# cat $DOTS/python/packages | xargs pip2 install --upgrade --user
cat $DOTS/python/packages | xargs pip3 install --upgrade --user
