# https://github.com/tkmpypy/dotfiles/blob/master/.config/efm-langserver/config.yaml
# https://github.com/lukas-reineke/dotfiles/blob/master/efm-langserver/config.yaml
# https://github.com/johejo/dotfiles/blob/master/efm-langserver/config.yaml

version: 2
log-file: "~/.local/share/nvim/efm.log"
log-level: 1
# root-markers:
#   - .git/
#   - mix.lock
#   - mix.exs
#   - package.json
#   - elm.json

tools:
  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  eslint: &eslint
    lint-command: './node_modules/.bin/eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true

  mix_credo: &mix_credo
    lint-command: "mix credo suggest --format=flycheck --read-from-stdin ${INPUT}"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %m'
    root-markers:
      - mix.lock
      - mix.exs

  prettier: &prettier
    format-command: './node_modules/.bin/prettier'

  golint: &golint
    lint-command: 'golint'
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %m'

  goimports: &goimports
    format-command: 'goimports'
    format-stdin: true

  black: &black
    format-command: 'black -'
    format-stdin: true

  isort: &isort
    format-command: 'isort --stdout -'
    format-stdin: true

  flake8: &flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  mypy: &mypy
    lint-command: 'mypy --show-column-numbers'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  terraform: &terraform
    format-command: 'terraform fmt -'
    format-stdin: true

  luafmt: &luafmt
    format-command: 'luafmt --indent-count 2 --stdin'
    format-stdin: true

  shellcheck: &shellcheck
    lint-command: 'shellcheck -f gcc -x -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

languages:
  vim:
    - <<: *vim-vint
  javascript:
    - <<: *eslint
    - <<: *prettier
  typescript:
    - <<: *eslint
    - <<: *prettier
  javascriptreact:
    - <<: *eslint
    - <<: *prettier
  typescriptreact:
    - <<: *eslint
    - <<: *prettier
  yaml:
    - <<: *prettier
  json:
    - <<: *prettier
  html:
    - <<: *prettier
  scss:
    - <<: *prettier
  css:
    - <<: *prettier
  markdown:
    - <<: *prettier
  go:
    - <<: *goimports
    - <<: *golint
  python:
    - <<: *black
    - <<: *isort
    - <<: *flake8
    - <<: *mypy
  tf:
    - <<: *terraform
  lua:
    - <<: *luafmt
  sh:
    - <<: *shellcheck
  elixir:
    - <<: *mix_credo
  eelixir:
    - <<: *mix_credo

# languages:
#   markdown:
#     lint-command: 'markdownlint -s'
#     lint-stdin: true
#     lint-formats:
#       - '%f:%l %m'

#   vim:
#     lint-command: 'vint -'
#     lint-stdin: true

#   ruby:
#     lint-command: 'rubocop --stdin'
#     lint-stdin: true
#     format-command: 'rubocop --safe-auto-correct --stdin - 2>/dev/null | sed "1,/^====================$/d"'

#   json:
#     format-command: 'jq .'

#   elixir:
#     lint-command: 'mix credo suggest --read-from-stdin'
#     lint-stdin: true

#   eelixir:
#     lint-command: 'mix credo suggest --read-from-stdin'
#     lint-stdin: true
