os:
    editPreset: "nvim"
gui:
    ## stuff relating to the UI
    scrollHeight: 2
    scrollPastBottom: true
    mouseEvents: true
    skipDiscardChangeWarning: false
    skipStashWarning: true
    nerdFontsVersion: "3"
    sidePanelWidth: 0.3333
    theme:
        lightTheme: false
        activeBorderColor:
            - green
            - bold
        inactiveBorderColor:
            - white
        optionsTextColor:
            - blue
        selectedLineBgColor:
            - black
        selectedRangeBgColor:
            - blue
    commitLength:
        show: true
services:
    "github-work": "github:github.com"
git:
    paging:
        colorArg: always
        pager: delta --dark --paging=never --24-bit-color=never
    merging:
        manualCommit: false
        args: ""
    skipHookPrefix: "WIP"
    autoFetch: true
update:
    method: prompt # can be: prompt | background | never
    days: 14 # how often a update is checked for
reporting: "off"
startuppopupversion: 1
splashUpdatesIndex: 0
confirmOnQuit: false
keybinding:
    universal:
        quit: "q"
        quit-alt1: "<c-c>"
        return: "<esc>"
        quitWithoutChangingDirectory: "Q"
        togglePanel: "<tab>"
        prevItem: "<up>"
        nextItem: "<down>"
        prevItem-alt: "k"
        nextItem-alt: "j"
        prevPage: ","
        nextPage: "."
        gotoTop: "<"
        gotoBottom: ">"
        prevBlock: "<left>"
        nextBlock: "<right>"
        prevBlock-alt: "h"
        nextBlock-alt: "l"
        nextMatch: "n"
        prevMatch: "N"
        startSearch: "/"
        optionMenu: "x"
        optionMenu-alt1: "?"
        select: "<space>"
        goInto: "<enter>"
        remove: "d"
        new: "n"
        edit: "e"
        openFile: "o"
        scrollUpMain: "<pgup>"
        scrollDownMain: "<pgdown>"
        scrollUpMain-alt1: "K"
        scrollDownMain-alt1: "J"
        scrollUpMain-alt2: "<c-u>"
        scrollDownMain-alt2: "<c-d>"
        executeShellCommand: ":"
        createRebaseOptionsMenu: "m"
        pushFiles: "P"
        pullFiles: "p"
        refresh: "R"
        createPatchOptionsMenu: "<c-p>"
        nextTab: "]"
        prevTab: "["
        nextScreenMode: "+"
        prevScreenMode: "_"
        undo: "z"
        redo: "<c-z>"
        filteringMenu: <c-s>
        diffingMenu: "<c-e>"
        copyToClipboard: "<c-o>"
    status:
        checkForUpdate: "u"
        recentRepos: "<enter>"
    files:
        commitChanges: "c"
        commitChangesWithoutHook: "w"
        amendLastCommit: "A"
        commitChangesWithEditor: "C"
        ignoreFile: "i"
        refreshFiles: "r"
        stashAllChanges: "s"
        viewStashOptions: "S"
        toggleStagedAll: "a"
        viewResetOptions: "D"
        fetch: "f"
    branches:
        createPullRequest: "o"
        checkoutBranchByName: "c"
        forceCheckoutBranch: "F"
        rebaseBranch: "r"
        renameBranch: "R"
        mergeIntoCurrentBranch: "M"
        viewGitFlowOptions: "i"
        fastForward: "f"
        pushTag: "P"
        setUpstream: "u"
        fetchRemote: "f"
    commits:
        squashDown: "s"
        renameCommit: "r"
        renameCommitWithEditor: "R"
        viewResetOptions: "g"
        markCommitAsFixup: "f"
        createFixupCommit: "F"
        squashAboveCommits: "S"
        moveDownCommit: "J"
        moveUpCommit: "K"
        amendToCommit: "A"
        pickCommit: "p"
        revertCommit: "t"
        cherryPickCopy: "c"
        cherryPickCopyRange: "C"
        pasteCommits: "v"
        tagCommit: "T"
        checkoutCommit: "<space>"
        resetCherryPick: "<c-R>"
    stash:
        popStash: "g"
    commitFiles:
        checkoutCommitFile: "c"
    main:
        toggleDragSelect: "v"
        toggleDragSelect-alt: "V"
        toggleSelectHunk: "a"
        pickBothHunks: "b"
# os:
#   editPreset: "nvim"
#
# # os:
# #   openCommand: open -- {{filename}}
# #   openLinkCommand: open {{link}}
# gui:
#   authorColors: {}
#   branchColors: {}
#   scrollHeight: 2
#   scrollPastBottom: true
#   mouseEvents: true
#   # skipUnstageLineWarning: false
#   skipStashWarning: false
#   sidePanelWidth: 0.3333
#   expandFocusedSidePanel: false
#   mainPanelSplitMode: flexible
#   language: auto
#   timeFormat: 02 Jan 06 15:04 MST
#   theme:
#     activeBorderColor:
#       - green
#       - bold
#     inactiveBorderColor:
#       - default
#     optionsTextColor:
#       - blue
#     selectedLineBgColor:
#       - blue
#     selectedRangeBgColor:
#       - blue
#     cherryPickedCommitBgColor:
#       - cyan
#     cherryPickedCommitFgColor:
#       - blue
#     unstagedChangesColor:
#       - red
#     defaultFgColor:
#       - black
#   commitLength:
#     show: true
#   # skipNoStagedFilesWarning: false
#   showListFooter: true
#   showFileTree: true
#   showRandomTip: false
#   showCommandLog: true
#   showBottomLine: true
#   nerdFontsVersion: "3"
#   commandLogSize: 8
#   splitDiff: auto
#   skipRewordInEditorWarning: false
#   windowSize: "normal"
# git:
#   paging:
#     colorArg: always
#     # pager: ""
#     useConfig: false
#   commit:
#     signOff: false
#     # verbose: default
#   merging:
#     manualCommit: false
#     args: ""
#   skipHookPrefix: WIP
#   autoFetch: true
#   autoRefresh: true
#   branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
#   allBranchesLogCmd: git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
#   overrideGpg: false
#   disableForcePushing: false
#   commitPrefixes: {}
#   parseEmoji: false
#   log:
#     order: topo-order
#     showGraph: when-maximised
#     showWholeGraph: false
#   diffContextSize: 3
# update:
#   method: prompt
#   days: 14
# refresher:
#   refreshInterval: 10
#   fetchInterval: 60
# confirmOnQuit: false
# quitOnTopLevelReturn: false
# keybinding:
#   universal:
#     quit: q
#     quit-alt1: <c-c>
#     return: <esc>
#     # return-alt1: ""
#     quitWithoutChangingDirectory: Q
#     togglePanel: <tab>
#     prevItem: <up>
#     nextItem: <down>
#     prevItem-alt: k
#     nextItem-alt: j
#     prevPage: ","
#     nextPage: .
#     scrollLeft: H
#     scrollRight: L
#     gotoTop: <
#     gotoBottom: ">"
#     prevBlock: <left>
#     nextBlock: <right>
#     prevBlock-alt: h
#     nextBlock-alt: l
#     # nextBlock-alt2: <tab>
#     # prevBlock-alt2: <backtab>
#     jumpToBlock:
#       - "1"
#       - "2"
#       - "3"
#       - "4"
#       - "5"
#     nextMatch: "n"
#     prevMatch: "N"
#     # startSearch: /
#     # optionMenu: x
#     optionMenu-alt1: "?"
#     select: <space>
#     goInto: <enter>
#     confirm: <enter>
#     # confirm-alt1: "y"
#     remove: d
#     new: "n"
#     edit: e
#     openFile: o
#     scrollUpMain: <pgup>
#     scrollDownMain: <pgdown>
#     scrollUpMain-alt1: K
#     scrollDownMain-alt1: J
#     scrollUpMain-alt2: <c-u>
#     scrollDownMain-alt2: <c-d>
#     executeCustomCommand: ":"
#     createRebaseOptionsMenu: m
#     pushFiles: P
#     pullFiles: p
#     refresh: R
#     createPatchOptionsMenu: <c-p>
#     nextTab: "]"
#     prevTab: "["
#     nextScreenMode: +
#     prevScreenMode: _
#     undo: z
#     redo: <c-z>
#     filteringMenu: <c-s>
#     diffingMenu: W
#     diffingMenu-alt: <c-e>
#     copyToClipboard: <c-o>
#     openRecentRepos: <c-r>
#     submitEditorText: <enter>
#     # appendNewline: <a-enter>
#     extrasMenu: "@"
#     toggleWhitespaceInDiffView: <c-w>
#     increaseContextInDiffView: "}"
#     decreaseContextInDiffView: "{"
#   status:
#     checkForUpdate: u
#     recentRepos: <enter>
#     # allBranchesLogGraph: a
#   files:
#     commitChanges: c
#     commitChangesWithoutHook: w
#     amendLastCommit: A
#     commitChangesWithEditor: C
#     ignoreFile: i
#     refreshFiles: r
#     stashAllChanges: s
#     viewStashOptions: S
#     toggleStagedAll: a
#     viewResetOptions: D
#     fetch: f
#     toggleTreeView: "`"
#     openMergeTool: M
#     openStatusFilter: <c-b>
#   branches:
#     createPullRequest: o
#     viewPullRequestOptions: O
#     # copyPullRequestURL: <c-y>
#     checkoutBranchByName: c
#     forceCheckoutBranch: F
#     rebaseBranch: r
#     renameBranch: R
#     mergeIntoCurrentBranch: M
#     viewGitFlowOptions: i
#     fastForward: f
#     pushTag: P
#     setUpstream: u
#     fetchRemote: f
#   commits:
#     squashDown: s
#     renameCommit: r
#     renameCommitWithEditor: R
#     viewResetOptions: g
#     markCommitAsFixup: f
#     createFixupCommit: F
#     squashAboveCommits: S
#     moveDownCommit: <c-j>
#     moveUpCommit: <c-k>
#     amendToCommit: A
#     # resetCommitAuthor: a
#     pickCommit: p
#     revertCommit: t
#     cherryPickCopy: c
#     cherryPickCopyRange: C
#     pasteCommits: v
#     tagCommit: T
#     checkoutCommit: <space>
#     resetCherryPick: <c-R>
#     # copyCommitAttributeToClipboard: "y"
#     openLogMenu: <c-l>
#     # openInBrowser: o
#     viewBisectOptions: b
#   stash:
#     popStash: g
#     renameStash: r
#   commitFiles:
#     checkoutCommitFile: c
#   main:
#     toggleDragSelect: v
#     toggleDragSelect-alt: V
#     toggleSelectHunk: a
#     pickBothHunks: b
#     # editSelectHunk: E
#   submodules:
#     init: i
#     update: u
#     bulkMenu: b
# disableStartupPopups: false
# customCommands: []
# services: {}
# notARepository: prompt
# promptToReturnFromSubprocess: false
