#!/usr/bin/env sh
source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items"     # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="JetBrainsMono Nerd Font Mono"                           # Needs to have Regular, Bold, Semibold, Heavy and Black variants
SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

PADDINGS=3 # All paddings use this value (icon, label, background and bar paddings)

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

SHADOW=on

# Setting up the general bar appearance and default values
sketchybar --bar height=32 \
  corner_radius=11 \
  border_width=0 \
  margin=10 \
  blur_radius=50 \
  position=top \
  padding_left=10 \
  padding_right=10 \
  color=$BAR_COLOR \
  topmost=off \
  font_smoothing=off \
  y_offset=10 \
  shadow=$SHADOW \
  notch_width=200 \
  --default drawing=on \
  updates=when_shown \
  label.font="$FONT:Semibold:13.0" \
  icon.font="$FONT:Bold:14.0" \
  icon.color=$ICON_COLOR \
  label.color=$LABEL_COLOR \
  icon.padding_left=$PADDINGS \
  icon.padding_right=$PADDINGS \
  label.padding_left=$PADDINGS \
  label.padding_right=$PADDINGS \
  background.padding_right=$PADDINGS \
  background.padding_left=$PADDINGS \
  popup.background.border_width=$POPUP_BORDER_WIDTH \
  popup.background.corner_radius=$POPUP_CORNER_RADIUS \
  popup.background.border_color=$POPUP_BORDER_COLOR \
  popup.background.color=$POPUP_BACKGROUND_COLOR \
  popup.background.shadow.drawing=$SHADOW

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/mail.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/cpu.sh"

############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."

# ############## BAR ##############
# sketchybar -m --bar \
#   height=32 \
#   position=top \
#   padding_left=0 \
#   padding_right=0 \
#   color=0xff3b4252 \
#   shadow=off \
#   topmost=off

# ############## GLOBAL DEFAULTS ##############
# sketchybar -m --default \
#   updates=when_shown \
#   drawing=on \
#   cache_scripts=on \
#   icon.font="JetBrainsMono Nerd Font Mono:Bold:18.0" \
#   icon.color=0xffffffff \
#   label.font="JetBrainsMono Nerd Font Mono:Bold:12.0" \
#   label.color=0xffeceff4 \
#   label.highlight_color=0xff8CABC8

# ############## SPACE DEFAULTS ##############
# sketchybar -m --default \
#   label.padding_left=5 \
#   label.padding_right=2 \
#   icon.padding_left=8 \
#   label.padding_right=8

# ############## PRIMARY DISPLAY SPACES ##############
# # SPACE 1: CODE ICON
# sketchybar -m --add space code left \
#   --set code icon= \
#   --set code associated_display=1 \
#   --set code associated_space=1 \
#   --set code icon.padding_left=5 \
#   --set code icon.padding_right=5 \
#   --set code label.padding_right=0 \
#   --set code label.padding_left=0 \
#   --set code label.color=0xffeceff4 \
#   --set code background.color=0xff57627A \
#   --set code background.height=21 \
#   --set code background.padding_left=12 \
#   --set code click_script="yabai -m space --focus 1" \
#   --set code script="~/.config/sketchybar/plugins/space.sh"

# # SPACE 2: WEB ICON
# sketchybar -m --add space web left \
#   --set web icon= \
#   --set web icon.highlight_color=0xff8CABC8 \
#   --set web associated_display=1 \
#   --set web associated_space=2 \
#   --set web icon.padding_left=5 \
#   --set web icon.padding_right=5 \
#   --set web label.padding_right=0 \
#   --set web label.padding_left=0 \
#   --set web label.color=0xffeceff4 \
#   --set web background.color=0xff57627A \
#   --set web background.height=21 \
#   --set web background.padding_left=7 \
#   --set web click_script="yabai -m space --focus 2" \
#   --set web script="~/.config/sketchybar/plugins/space.sh"

# # SPACE 3: HOME ICON
# sketchybar -m --add space home left \
#   --set home icon= \
#   --set home icon.highlight_color=0xff8CABC8 \
#   --set home associated_display=1 \
#   --set home associated_space=3 \
#   --set home icon.padding_left=5 \
#   --set home icon.padding_right=5 \
#   --set home label.padding_right=0 \
#   --set home label.padding_left=0 \
#   --set home label.color=0xffeceff4 \
#   --set home background.color=0xff57627A \
#   --set home background.height=21 \
#   --set home background.padding_left=7 \
#   --set home click_script="yabai -m space --focus 3" \
#   --set home script="~/.config/sketchybar/plugins/space.sh"

# # SPACE 4: CHAT ICON
# sketchybar -m --add space chat left \
#   --set chat icon= \
#   --set chat icon.highlight_color=0xff8CABC8 \
#   --set chat associated_display=1 \
#   --set chat associated_space=4 \
#   --set chat icon.padding_left=5 \
#   --set chat icon.padding_right=5 \
#   --set chat label.padding_right=0 \
#   --set chat label.padding_left=0 \
#   --set chat label.color=0xffeceff4 \
#   --set chat background.color=0xff57627A \
#   --set chat background.height=21 \
#   --set chat background.padding_left=7 \
#   --set chat click_script="yabai -m space --focus 4" \
#   --set chat script="~/.config/sketchybar/plugins/space.sh"

# # SPACE 5: MUSIC ICON
# sketchybar -m --add space music left \
#   --set music icon= \
#   --set music icon.highlight_color=0xff8CABC8 \
#   --set music associated_display=1 \
#   --set music associated_space=5 \
#   --set music icon.padding_left=5 \
#   --set music icon.padding_right=5 \
#   --set music label.padding_right=0 \
#   --set music label.padding_left=0 \
#   --set music label.color=0xffeceff4 \
#   --set music background.color=0xff57627A \
#   --set music background.height=21 \
#   --set music background.padding_left=7 \
#   --set music click_script="yabai -m space --focus 5" \
#   --set music script="~/.config/sketchybar/plugins/space.sh"

# # SPACE 6: OTHER ICON
# sketchybar -m --add space other left \
#   --set other icon= \
#   --set other icon.highlight_color=0xff8CABC8 \
#   --set other associated_display=1 \
#   --set other associated_space=6 \
#   --set other icon.padding_left=5 \
#   --set other icon.padding_right=5 \
#   --set other label.padding_right=0 \
#   --set other label.padding_left=0 \
#   --set other label.color=0xffeceff4 \
#   --set other background.color=0xff57627A \
#   --set other background.height=21 \
#   --set other background.padding_left=7 \
#   --set other click_script="yabai -m space --focus 6" \
#   --set other script="~/.config/sketchybar/plugins/space.sh"

# # WINDOW TITLE
# sketchybar -m --add item title left \
#   --set title icon= \
#   --set title label.padding_left=9 \
#   --set title background.color=0xff57627A \
#   --set title background.height=21 \
#   --set title background.padding_left=7 \
#   --set title script="~/.config/sketchybar/plugins/window_title.sh" \
#   --set title update_freq=0 \
#   --subscribe title window_focus front_app_switched space_change title_change

# ############## ITEM DEFAULTS ###############
# sketchybar -m --default \
#   label.padding_left=2 \
#   icon.padding_right=2 \
#   icon.padding_left=6 \
#   label.padding_right=6

# ############## RIGHT ITEMS ##############
# # DATE TIME
# sketchybar -m --add item date_time right \
#   --set date_time icon= \
#   --set date_time icon.padding_left=8 \
#   --set date_time icon.padding_right=0 \
#   --set date_time label.padding_right=9 \
#   --set date_time label.padding_left=6 \
#   --set date_time label.color=0xffeceff4 \
#   --set date_time update_freq=20 \
#   --set date_time background.color=0xff57627A \
#   --set date_time background.height=21 \
#   --set date_time background.padding_right=12 \
#   --set date_time script="~/.config/sketchybar/plugins/date_time.sh"

# # RAM USAGE
# sketchybar -m --add item topmem right \
#   --set topmem icon= \
#   --set topmem icon.padding_left=8 \
#   --set topmem icon.padding_right=0 \
#   --set topmem label.padding_right=8 \
#   --set topmem label.padding_left=6 \
#   --set topmem label.color=0xffeceff4 \
#   --set topmem background.color=0xff57627A \
#   --set topmem background.height=21 \
#   --set topmem background.padding_right=7 \
#   --set topmem update_freq=2 \
#   --set topmem script="~/.config/sketchybar/plugins/topmem.sh"

# # CPU USAGE
# sketchybar -m --add item cpu_percent right \
#   --set cpu_percent icon= \
#   --set cpu_percent icon.padding_left=8 \
#   --set cpu_percent icon.padding_right=0 \
#   --set cpu_percent label.padding_right=8 \
#   --set cpu_percent label.padding_left=6 \
#   --set cpu_percent label.color=0xffeceff4 \
#   --set cpu_percent background.color=0xff57627A \
#   --set cpu_percent background.height=21 \
#   --set cpu_percent background.padding_right=7 \
#   --set cpu_percent update_freq=2 \
#   --set cpu_percent script="~/.config/sketchybar/plugins/cpu.sh"

# # MIC STATUS
# sketchybar -m --add item mic right \
#   --set mic icon.padding_left=8 \
#   --set mic icon.padding_right=8 \
#   --set mic label.padding_right=0 \
#   --set mic label.padding_left=0 \
#   --set mic label.color=0xffeceff4 \
#   --set mic background.color=0xff57627A \
#   --set mic background.height=21 \
#   --set mic background.padding_right=7 \
#   --set mic update_freq=3 \
#   --set mic script="~/.config/sketchybar/plugins/mic.sh" \
#   --set mic click_script="~/.config/sketchybar/plugins/mic_click.sh"

# # TOP PROCESS
# sketchybar -m --add item topproc right \
#   --set topproc drawing=off \
#   --set topproc label.padding_right=10 \
#   --set topproc update_freq=15 \
#   --set topproc script="~/.config/sketchybar/plugins/topproc.sh"

# ###################### CENTER ITEMS ###################
# # CURRENT SPOTIFY SONG
# # Adding custom events which can listen on distributed notifications from other running processes
# sketchybar -m --add event spotify_change "com.spotify.client.PlaybackStateChanged" \
#   --add item spotifyIndicator left \
#   --set spotifyIndicator background.color=0xff57627A \
#   --set spotifyIndicator background.height=21 \
#   --set spotifyIndicator background.padding_left=7 \
#   --set spotifyIndicator script="~/.config/sketchybar/plugins/spotify_indicator.sh" \
#   --set spotifyIndicator click_script="osascript -e 'tell application \"Spotify\" to pause'" \
#   --subscribe spotifyIndicator spotify_change

# ############## FINALIZING THE SETUP ##############
# sketchybar -m --update

# echo "sketchybar configuration loaded.."
