#!/usr/bin/env bash

# NOTE: this script is for use with tmux _ONLY_
#

ptt_mode=$(hs -c "require('ptt').currentMode()")

echo

if [[ "$ptt_mode" == "push-to-talk" ]]; then
  printf "󰍭 muted" # alts: 󰚎󰂠󰒲󱋑󱋒󰪓⏾󰤄 \uf59f
elif [[ "$ptt_mode" == "push-to-mute" ]]; then
  printf "#[fg=#e67e80]◉ unmuted" # alts: 󰚎󰂠󰒲󱋑󱋒󰪓⏾󰤄 \uf59f
fi
